-- 저자ID,저자명,카테고리,매출액/A,B,S/2022년1월/저자별 카테고리별 매출
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS S
JOIN BOOK AS B USING (BOOK_ID)
JOIN AUTHOR AS A USING (AUTHOR_ID)
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;