-- ID,이름/IN OUT JOIN(ID)/보호기간 긴 동물 TOP2/보호기간 내림차순 정렬
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
     JOIN ANIMAL_OUTS O USING(ANIMAL_ID)
ORDER BY TIMESTAMPDIFF(SECOND,I.DATETIME,O.DATETIME) DESC
LIMIT 2;