-- 두 테이블에서 년,월,성별 별 상품 구매 회원수 집계/ 년,월,성별 오름차순/ 성별 정보 NULL
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE)  MONTH, GENDER, COUNT(DISTINCT USER_ID) USERS
FROM USER_INFO
JOIN ONLINE_SALE USING(USER_ID)
WHERE GENDER IS NOT NULL 
GROUP BY YEAR, MONTH, GENDER;