-- 2021가입 중 구매회원수,구매회원비율/년,월 별 출력/년 오름차순,월 오름차순
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT USER_ID) PUCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(USER_ID) 
                                      FROM USER_INFO 
                                      WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM USER_INFO U JOIN ONLINE_SALE O USING (USER_ID)
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH