-- ID,닉네임,총거래금액/B,U/완료된 총 거래금액 70만원 이상/총 거래금액 오름차순 정렬
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B
     JOIN USED_GOODS_USER AS U ON B.WRITER_ID=U.USER_ID
WHERE B.STATUS='DONE'
GROUP BY B.WRITER_ID
HAVING TOTAL_SALES>=700000
ORDER BY TOTAL_SALES