-- FLAVOR/FIRST_HALF,ICECREAM_INFO/총주문량 3,000초과, 주 성분 과일/총주문량 내림차순
SELECT FLAVOR
FROM FIRST_HALF AS F JOIN ICECREAM_INFO AS I USING(FLAVOR)
WHERE TOTAL_ORDER>3000 AND INGREDIENT_TYPE='fruit_based'
ORDER BY TOTAL_ORDER DESC;