-- ID,저자명,출판일/경제 카테고리/출판일 오름차순
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B
     JOIN AUTHOR A USING(AUTHOR_ID)
WHERE CATEGORY='경제'
ORDER BY PUBLISHED_DATE;